### PR TITLE
[3.0] Layout components

### PR DESCRIPTION
**Pull request by SiravitPhokeed**
image

**Features**
- New components
  - Columns
  - Divider
  - Header
  - Root Layout
  - Page Header
  - Section
- Migrated typography to `mixin` and `include` instead of `extend`
- Restructured `abstracts` files to significantly reduce bundle size
  - Reduced generated duplicate styles
  - Migrated to ThemeProvider instead of importing `palette.scss` on every SCSS file
- Top-level page transition
- `useScrollDirection` hook
- Demo global styles

**Fixes**
- Actions CSS missing documentation
- Navigation Drawer Item autofocus is always visible, even when the user entered the Drawer with means other than a keyboard
- Navigation Drawer doesn’t close when a Navigation Drawer Item is clicked
- Material Icon and Segmented Button have wrong `displayName`s

### CODE REVIEW

**Review by Jimmy-Tempest — APPROVED** [review]
LGTM!!!
Would prefer a smaller PR tho

**Comment by SiravitPhokeed** [comment]
Didn’t you say last time that 3,000-4,000 lines was the standard? How many would you prefer?

**Comment by Jimmy-Tempest** [comment]
I said 200 to 300 is a big PR ;-;

**Comment by Jimmy-Tempest** [comment]
And 1000 would be quite the size with commends and other files included

**Comment by SiravitPhokeed** [comment]
Well too bad.

**Pull request merged**
